trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
  - name: users
    type: object
    default: [john, jane, bob]

jobs:
- job: LoopOverUsers
  steps:
  - ${{ each user in parameters.users }}:
    - script: echo "Processing user:" ${{ user }}