trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  environments: []

jobs:
- template: deploy-template.yml
  parameters:
    environments:
      - name: 'Dev'
        shards:
          - shard: 'dev-shard1'
            connectionString: 'Server=myserver;Database=dev_shard1;User Id=myuser;Password=mypassword;'
          - shard: 'dev-shard2'
            connectionString: 'Server=myserver;Database=dev_shard2;User Id=myuser;Password=mypassword;'
      - name: 'Test'
        shards:
          - shard: 'test-shard1'
            connectionString: 'Server=myserver;Database=test_shard1;User Id=myuser;Password=mypassword;'
          - shard: 'test-shard2'
            connectionString: 'Server=myserver;Database=test_shard2;User Id=myuser;Password=mypassword;'
          - shard: 'test-shard3'
            connectionString: 'Server=myserver;Database=test_shard3;User Id=myuser;Password=mypassword;'
          - shard: 'test-shard4'
            connectionString: 'Server=myserver;Database=test_shard4;User Id=myuser;Password=mypassword;'