trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
  - name: databaseEnvironments
    type: object
    default: 
      dev: 
        name: "dev"
        shards: [shard1, shard2]
      test: 
        name: "test"
        shards: [shard1, shard2, shard3]
      lnp: 
        name: "test"
        shards: [shard1, shard2, shard3, shard4]



jobs:
- job: ForEachTest 
  steps:
  - ${{ each database in parameters.databaseEnvironments }}:
    - script: echo "Processing environmet:" ${{ database.name }} "---- ----"