trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: environmentSettings
  type: object
  default: 
  - environmentName: 'dev'
    shards: ['shard1', 'shard2']
  - environmentName: 'uat'
    shards: ['shard1', 'shard2', 'shard2']


steps:
- ${{ each environmentSetting in parameters.environmentSettings }}: 
  - ${{ each shard in environmentSetting.shards }}:
    - script: echo ${{ shard }}