trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: databaseEnvironments
  type: object
  default: 
  - environmentName: 'dev'
    shards: 
      - shard: 
        name: 'shard1'
        connectionString: 'paprika1'
      - shard:
        name: 'shard2'
        connectionString: 'paprika2'
  - environmentName: 'test'
    shards: 
      - shard: 
        name: 'shard1'
        connectionString: 'paprika1'
      - shard: 
        name: 'shard2'
        connectionString: 'paprika2'
      - shard:
        name: 'shard3'
        connectionString: 'paprika3'


steps:
- ${{ each databaseEnvironment in parameters.databaseEnvironments }}: 
  - ${{ each shard in databaseEnvironment.shards }}:
    - script: echo "Environment:" ${{ databaseEnvironment.environmentName }} "Shard:" ${{ shard.name }} "connectionString:" ${{shard.connectionString}}